---
version: '3'
services:
  postgresql:
    image: postgres:12-alpine
    container_name: one1
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust