--liquibase formatted sql
--changeset ssosnovenko:v_006 dbms:postgresql
--preconditions onFail:HALT onError:HALT

CREATE TABLE IF NOT EXISTS test_market.address
(
    id                  BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT,
    phone               TEXT,
    description         TEXT
);
